language: node_js
node_js:
  - "7"

addons:
  sonarcloud:
    organization: "conoce-tu-congreso"
    token: "$SONAR_TOKEN"

script:
  - yarn build
  - yarn lint
  - yarn test
  - sonar-scanner

branches:
  only:
    - master
    - develop
